import type { BigScreenComponentType, BigScreenDataBindingConfig } from '@/types/bigScreen'
import { chartComponentRegistry } from './chartComponentRegistry'
import { threeDComponentRegistry } from './threeDComponentRegistry'

export type DefaultComponentCategory = '文本' | '图形' | '媒体' | '时间' | '容器' | '控件' | '图表' | '场景'

export interface DefaultComponentRegistryItem {
  type: BigScreenComponentType
  name: string
  category: DefaultComponentCategory
  width: number
  height: number
  style: Record<string, unknown>
  dataBinding?: BigScreenDataBindingConfig
}

export const defaultComponentRegistry: DefaultComponentRegistryItem[] = [
  {
    type: 'title',
    name: '标题',
    category: '文本',
    width: 420,
    height: 72,
    style: {
      text: '数字大屏标题',
      fontSize: 36,
      fontWeight: 700,
      color: '#f8fafc',
      textAlign: 'left',
      letterSpacing: 0,
      scrollEnabled: false,
      scrollSpeed: 40,
    },
  },
  {
    type: 'singleText',
    name: '单行文本',
    category: '文本',
    width: 360,
    height: 48,
    style: {
      text: '单行说明文本',
      fontSize: 20,
      fontWeight: 400,
      color: '#cbd5e1',
      textAlign: 'left',
      letterSpacing: 0,
      scrollEnabled: false,
      scrollDirection: 'left',
      scrollSpeed: 40,
    },
  },
  {
    type: 'multiText',
    name: '多行文本',
    category: '文本',
    width: 420,
    height: 128,
    style: {
      text: '多行文本用于展示说明、结论或业务备注。',
      fontSize: 18,
      fontWeight: 400,
      lineHeight: 1.6,
      color: '#cbd5e1',
      textAlign: 'left',
      scrollEnabled: false,
      scrollDirection: 'up',
      scrollSpeed: 30,
    },
  },
  {
    type: 'rectangle',
    name: '矩形',
    category: '图形',
    width: 360,
    height: 180,
    style: {
      backgroundColor: 'rgba(15, 47, 81, 0.72)',
      backgroundImage: '',
      borderColor: '#38bdf8',
      borderWidth: 1,
      borderRadius: 8,
      borderStyle: 'solid',
      blur: 0,
      shadow: '0 18px 60px rgba(14, 165, 233, 0.16)',
    },
  },
  {
    type: 'circle',
    name: '圆形',
    category: '图形',
    width: 180,
    height: 180,
    style: {
      backgroundColor: 'rgba(14, 165, 233, 0.32)',
      backgroundImage: '',
      borderColor: '#7dd3fc',
      borderWidth: 2,
      borderStyle: 'solid',
      blur: 0,
      shadow: '0 18px 60px rgba(14, 165, 233, 0.16)',
    },
  },
  {
    type: 'image',
    name: '图片',
    category: '媒体',
    width: 360,
    height: 220,
    style: {
      imageUrl: '',
      objectFit: 'cover',
      placeholderText: '图片占位',
    },
  },
  {
    type: 'video',
    name: '普通视频',
    category: '媒体',
    width: 480,
    height: 270,
    style: {
      videoUrl: '',
      autoplay: false,
      loop: true,
      muted: true,
      controls: true,
      posterUrl: '',
    },
  },
  {
    type: 'iframe',
    name: '网页',
    category: '媒体',
    width: 560,
    height: 320,
    style: {
      url: 'https://example.com',
      sandbox: 'allow-scripts allow-same-origin allow-forms',
      allowInteraction: true,
    },
  },
  {
    type: 'hotspot',
    name: '热区',
    category: '媒体',
    width: 180,
    height: 120,
    style: {
      editMaskColor: 'rgba(56, 189, 248, 0.18)',
      borderColor: '#38bdf8',
      actionLabel: '点击热区',
    },
  },
  {
    type: 'videoStream',
    name: '视频流播放器',
    category: '媒体',
    width: 480,
    height: 270,
    style: {
      streamUrl: '',
      streamType: 'hls',
      stylePanelUrl: '',
      reconnectEnabled: true,
      reconnectIntervalSeconds: 5,
      hiddenUnmount: true,
      muted: true,
      controls: true,
      errorText: '视频流未连接',
    },
    dataBinding: {
      sourceType: 'static',
      sourceId: '',
      fields: [{ slot: 'videoUrl', fieldName: 'videoUrl', fieldType: 'dimension' }],
      updateMode: 'manual',
      staticRows: [{ videoUrl: '' }],
    },
  },
  {
    type: 'datetime',
    name: '日期时间',
    category: '时间',
    width: 300,
    height: 56,
    style: {
      format: 'YYYY-MM-DD HH:mm:ss',
      timezone: 'local',
      fontSize: 24,
      color: '#e2e8f0',
      textAlign: 'left',
      updateIntervalSeconds: 1,
    },
  },
  {
    type: 'date',
    name: '日期',
    category: '时间',
    width: 220,
    height: 52,
    style: {
      format: 'YYYY-MM-DD',
      timezone: 'local',
      fontSize: 24,
      color: '#e2e8f0',
      textAlign: 'left',
      updateIntervalSeconds: 60,
    },
  },
  {
    type: 'time',
    name: '时间',
    category: '时间',
    width: 180,
    height: 52,
    style: {
      format: 'HH:mm:ss',
      timezone: 'local',
      fontSize: 28,
      color: '#e2e8f0',
      textAlign: 'left',
      updateIntervalSeconds: 1,
    },
  },
  {
    type: 'weekday',
    name: '星期',
    category: '时间',
    width: 150,
    height: 52,
    style: {
      format: 'dddd',
      timezone: 'local',
      fontSize: 24,
      color: '#e2e8f0',
      textAlign: 'left',
      updateIntervalSeconds: 60,
    },
  },
  {
    type: 'repeater',
    name: '重复器',
    category: '容器',
    width: 620,
    height: 260,
    style: {
      direction: 'row',
      itemsPerLine: 3,
      horizontalGap: 12,
      verticalGap: 12,
      paginationEnabled: true,
      pageSize: 6,
      currentPage: 1,
      templateName: '重复项模板',
      itemBackground: 'rgba(15, 47, 81, 0.72)',
      itemBorderColor: '#38bdf8',
      sampleRows: [
        { title: '华东区域', value: '12,860', status: '正常' },
        { title: '华南区域', value: '9,420', status: '关注' },
        { title: '西南区域', value: '6,210', status: '提升' },
      ],
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'title', fieldName: 'title', fieldType: 'dimension' },
        { slot: 'value', fieldName: 'value', fieldType: 'measure', aggregation: 'sum' },
        { slot: 'status', fieldName: 'status', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10, measureField: 'value' },
      staticRows: [
        { title: '华东区域', value: 12860, status: '正常' },
        { title: '华南区域', value: 9420, status: '关注' },
        { title: '西南区域', value: 6210, status: '提升' },
        { title: '华北区域', value: 5840, status: '关注' },
      ],
    },
  },
  {
    type: 'carousel',
    name: '轮播器',
    category: '容器',
    width: 560,
    height: 300,
    style: {
      autoplay: true,
      intervalSeconds: 4,
      indicatorVisible: true,
      indicatorPosition: 'bottom',
      activePanelId: 'panel-1',
      panels: [
        { id: 'panel-1', name: 'Panel 1', title: '经营看板', description: '展示核心经营指标' },
        { id: 'panel-2', name: 'Panel 2', title: '风险预警', description: '展示异常与待处理事项' },
      ],
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'id', fieldName: 'id', fieldType: 'dimension' },
        { slot: 'title', fieldName: 'title', fieldType: 'dimension' },
        { slot: 'description', fieldName: 'description', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { id: 'panel-1', name: '经营', title: '经营看板', description: '展示核心经营指标' },
        { id: 'panel-2', name: '风险', title: '风险预警', description: '展示异常与待处理事项' },
      ],
    },
  },
  {
    type: 'tabs',
    name: '标签页',
    category: '容器',
    width: 620,
    height: 320,
    style: {
      headerVisible: true,
      autoPlay: false,
      intervalSeconds: 5,
      activeTabId: 'tab-1',
      headerBackground: 'rgba(15, 23, 42, 0.88)',
      activeColor: '#38bdf8',
      panels: [
        { id: 'tab-1', name: '总览', title: '总览内容' },
        { id: 'tab-2', name: '明细', title: '明细内容' },
      ],
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'id', fieldName: 'id', fieldType: 'dimension' },
        { slot: 'name', fieldName: 'name', fieldType: 'dimension' },
        { slot: 'title', fieldName: 'title', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { id: 'tab-1', name: '总览', title: '总览内容' },
        { id: 'tab-2', name: '明细', title: '明细内容' },
      ],
    },
  },
  {
    type: 'select',
    name: '下拉选择器',
    category: '控件',
    width: 260,
    height: 48,
    style: {
      placeholder: '请选择',
      searchable: true,
      value: 'all',
      options: [
        { label: '全部', value: 'all' },
        { label: '华东', value: 'east' },
        { label: '华南', value: 'south' },
      ],
      backgroundColor: 'rgba(15, 23, 42, 0.86)',
      borderColor: '#38bdf8',
      color: '#e2e8f0',
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'label', fieldName: 'label', fieldType: 'dimension' },
        { slot: 'value', fieldName: 'value', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { label: '全部', value: 'all' },
        { label: '华东', value: 'east' },
        { label: '华南', value: 'south' },
      ],
    },
  },
  {
    type: 'multiSelect',
    name: '多选下拉框',
    category: '控件',
    width: 300,
    height: 48,
    style: {
      placeholder: '请选择多个值',
      value: ['east', 'south'],
      options: [
        { label: '华东', value: 'east' },
        { label: '华南', value: 'south' },
        { label: '西南', value: 'west' },
      ],
      enableSelectAll: true,
      enableInvert: true,
      enableClear: true,
      backgroundColor: 'rgba(15, 23, 42, 0.86)',
      borderColor: '#38bdf8',
      color: '#e2e8f0',
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'label', fieldName: 'label', fieldType: 'dimension' },
        { slot: 'value', fieldName: 'value', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { label: '华东', value: 'east' },
        { label: '华南', value: 'south' },
        { label: '西南', value: 'west' },
      ],
    },
  },
  {
    type: 'treeSelect',
    name: '树状下拉选择器',
    category: '控件',
    width: 320,
    height: 52,
    style: {
      placeholder: '请选择层级节点',
      value: 'hangzhou',
      autoExpand: true,
      treeData: [
        {
          label: '浙江',
          value: 'zhejiang',
          children: [{ label: '杭州', value: 'hangzhou' }, { label: '宁波', value: 'ningbo' }],
        },
      ],
      backgroundColor: 'rgba(15, 23, 42, 0.86)',
      borderColor: '#38bdf8',
      color: '#e2e8f0',
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'label', fieldName: 'label', fieldType: 'dimension' },
        { slot: 'value', fieldName: 'value', fieldType: 'dimension' },
        { slot: 'parentValue', fieldName: 'parentValue', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { label: '浙江', value: 'zhejiang', parentValue: '' },
        { label: '杭州', value: 'hangzhou', parentValue: 'zhejiang' },
        { label: '宁波', value: 'ningbo', parentValue: 'zhejiang' },
      ],
    },
  },
  {
    type: 'treeMultiSelect',
    name: '树状多选下拉框',
    category: '控件',
    width: 340,
    height: 52,
    style: {
      placeholder: '请选择多个层级节点',
      value: ['hangzhou', 'ningbo'],
      autoCheckChildren: true,
      enableSelectAll: true,
      enableInvert: true,
      enableClear: true,
      treeData: [
        {
          label: '浙江',
          value: 'zhejiang',
          children: [{ label: '杭州', value: 'hangzhou' }, { label: '宁波', value: 'ningbo' }],
        },
      ],
      backgroundColor: 'rgba(15, 23, 42, 0.86)',
      borderColor: '#38bdf8',
      color: '#e2e8f0',
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'label', fieldName: 'label', fieldType: 'dimension' },
        { slot: 'value', fieldName: 'value', fieldType: 'dimension' },
        { slot: 'parentValue', fieldName: 'parentValue', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { label: '浙江', value: 'zhejiang', parentValue: '' },
        { label: '杭州', value: 'hangzhou', parentValue: 'zhejiang' },
        { label: '宁波', value: 'ningbo', parentValue: 'zhejiang' },
      ],
    },
  },
  {
    type: 'datePicker',
    name: '日期选择器',
    category: '控件',
    width: 260,
    height: 52,
    style: {
      mode: 'date',
      value: '2026-05-25',
      minDate: '2026-01-01',
      maxDate: '2026-12-31',
      availableDatesField: '',
      backgroundColor: 'rgba(15, 23, 42, 0.86)',
      borderColor: '#38bdf8',
      color: '#e2e8f0',
    },
    dataBinding: {
      sourceType: 'static',
      fields: [
        { slot: 'date', fieldName: 'date', fieldType: 'date' },
        { slot: 'enabled', fieldName: 'enabled', fieldType: 'dimension' },
      ],
      updateMode: 'manual',
      sortRules: [{ fieldName: 'date', order: 'asc' }],
      filterRules: [],
      topN: { enabled: false, mode: 'all', count: 10 },
      staticRows: [
        { date: '2026-05-25', enabled: true },
        { date: '2026-05-26', enabled: true },
      ],
    },
  },
  ...chartComponentRegistry,
  ...threeDComponentRegistry,
]

export const defaultComponentCategories: DefaultComponentCategory[] = [
  '文本',
  '图形',
  '媒体',
  '时间',
  '容器',
  '控件',
  '图表',
  '场景',
]
